[package]
name = "blerg"
version = "0.1.0"
authors = ["Mike Mull <mike.mull@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.4"
clap = "4.6"
ctrlc = "3.5"
postgres = "0.19"
postgres-types = "0.2"
bytes = "1"
humantime = "2.4"

[dependencies.pnet]
version = "0.35"